# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CalcularCuadradoArray(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cuadrado: int=None, original: int=None):  # noqa: E501
        """CalcularCuadradoArray - a model defined in Swagger

        :param cuadrado: The cuadrado of this CalcularCuadradoArray.  # noqa: E501
        :type cuadrado: int
        :param original: The original of this CalcularCuadradoArray.  # noqa: E501
        :type original: int
        """
        self.swagger_types = {
            'cuadrado': int,
            'original': int
        }

        self.attribute_map = {
            'cuadrado': 'cuadrado',
            'original': 'original'
        }

        self._cuadrado = cuadrado
        self._original = original

    @classmethod
    def from_dict(cls, dikt) -> 'CalcularCuadradoArray':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Calcular_cuadrado_array of this CalcularCuadradoArray.  # noqa: E501
        :rtype: CalcularCuadradoArray
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cuadrado(self) -> int:
        """Gets the cuadrado of this CalcularCuadradoArray.


        :return: The cuadrado of this CalcularCuadradoArray.
        :rtype: int
        """
        return self._cuadrado

    @cuadrado.setter
    def cuadrado(self, cuadrado: int):
        """Sets the cuadrado of this CalcularCuadradoArray.


        :param cuadrado: The cuadrado of this CalcularCuadradoArray.
        :type cuadrado: int
        """

        self._cuadrado = cuadrado

    @property
    def original(self) -> int:
        """Gets the original of this CalcularCuadradoArray.


        :return: The original of this CalcularCuadradoArray.
        :rtype: int
        """
        return self._original

    @original.setter
    def original(self, original: int):
        """Sets the original of this CalcularCuadradoArray.


        :param original: The original of this CalcularCuadradoArray.
        :type original: int
        """

        self._original = original
