# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CalcularMediaResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, media: float=None):  # noqa: E501
        """CalcularMediaResponse200 - a model defined in Swagger

        :param media: The media of this CalcularMediaResponse200.  # noqa: E501
        :type media: float
        """
        self.swagger_types = {
            'media': float
        }

        self.attribute_map = {
            'media': 'media'
        }

        self._media = media

    @classmethod
    def from_dict(cls, dikt) -> 'CalcularMediaResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Calcular_media_response_200 of this CalcularMediaResponse200.  # noqa: E501
        :rtype: CalcularMediaResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def media(self) -> float:
        """Gets the media of this CalcularMediaResponse200.


        :return: The media of this CalcularMediaResponse200.
        :rtype: float
        """
        return self._media

    @media.setter
    def media(self, media: float):
        """Sets the media of this CalcularMediaResponse200.


        :param media: The media of this CalcularMediaResponse200.
        :type media: float
        """

        self._media = media
