---
swagger: "2.0"
info:
  description: ""
  version: "1"
  title: "Prueba Flask"
paths:
  /media:
    post:
      tags:
      - "media"
      summary: "Devuelve la media de los números introducidos"
      operationId: "media_post"
      parameters:
      - in: "body"
        name: "numeros"
        description: "La media de los números a devolver"
        required: true
        schema:
          $ref: "#/definitions/Calcular_media_post"
      responses:
        "200":
          description: "JSON con la media de los números"
          schema:
            $ref: "#/definitions/Calcular_media_response_200"
        "400":
          description: "No es un número válido"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "No se encuentra la ruta"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.media_controller"
  /media_csv_url:
    post:
      tags:
      - "media"
      summary: "Devuelve la media de los números en un csv"
      operationId: "media_csv_url_post"
      parameters:
      - in: "body"
        name: "url"
        description: "url donde se encuentra el csv"
        required: true
        schema:
          $ref: "#/definitions/Calcular_media_csv_url"
      responses:
        "200":
          description: "JSON con la media de los números"
          schema:
            $ref: "#/definitions/Calcular_media_response_200"
        "400":
          description: "No es un número válido"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "No se encuentra la ruta"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.media_controller"
  /cuadrados/{numeros}:
    post:
      tags:
      - "cuadrado"
      summary: "Devuelve el cuadrado de los números introducidos"
      operationId: "cuadrados_numeros_post"
      parameters:
      - name: "numeros"
        in: "path"
        required: true
        type: "array"
        items:
          type: "number"
        collectionFormat: "csv"
      responses:
        "200":
          description: "JSON con el valor de los cuadrados y el total"
          schema:
            $ref: "#/definitions/Calcular_cuadrado_response"
        "400":
          description: "No es un número válido"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "No se encuentra la ruta"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "swagger_server.controllers.cuadrado_controller"
definitions:
  Calcular_media_post:
    type: "object"
    required:
    - "numeros"
    - "redondear"
    properties:
      numeros:
        type: "array"
        items:
          example: "1.0, 4.34, 9.0"
      redondear:
        type: "boolean"
        example: false
  Calcular_media_csv_url:
    type: "object"
    required:
    - "redondear"
    - "url"
    properties:
      url:
        type: "string"
        example: "https://repo/fichero.csv"
      redondear:
        type: "boolean"
        example: false
  Calcular_media_response_200:
    type: "object"
    properties:
      media:
        type: "number"
        example: 4.78
    example:
      media: 4.78
  Calcular_cuadrado_response:
    type: "object"
    properties:
      resultados:
        type: "array"
        items:
          $ref: "#/definitions/Calcular_cuadrado_array"
      total:
        type: "number"
        example: 1.0
    example:
      total: 1.0
      resultados:
      - original: 2
        cuadrado: 4
      - original: 2
        cuadrado: 4
  Calcular_cuadrado_array:
    type: "object"
    properties:
      cuadrado:
        type: "integer"
        example: 4
      original:
        type: "integer"
        example: 2
    example:
      original: 2
      cuadrado: 4
  Error:
    type: "object"
    required:
    - "error"
    properties:
      error:
        type: "string"
        example: "Unexpected error"
